/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eAdWhirl_autodefs.h"
#include "s3eEdk.h"
#include "s3eAdWhirl.h"
//Declarations of Init and Term functions
extern s3eResult s3eAdWhirlInit();
extern void s3eAdWhirlTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult s3eAdWhirlStart_wrap(const char* appKey)
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl func on main thread: s3eAdWhirlStart"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eAdWhirlStart, 1, appKey);
}

static s3eResult s3eAdWhirlRequestFreshAd_wrap()
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl func on main thread: s3eAdWhirlRequestFreshAd"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eAdWhirlRequestFreshAd, 0);
}

static s3eResult s3eAdWhirlShow_wrap()
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl func on main thread: s3eAdWhirlShow"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eAdWhirlShow, 0);
}

static s3eResult s3eAdWhirlHide_wrap()
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl func on main thread: s3eAdWhirlHide"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eAdWhirlHide, 0);
}

#define s3eAdWhirlStart s3eAdWhirlStart_wrap
#define s3eAdWhirlRequestFreshAd s3eAdWhirlRequestFreshAd_wrap
#define s3eAdWhirlShow s3eAdWhirlShow_wrap
#define s3eAdWhirlHide s3eAdWhirlHide_wrap

#endif

s3eResult s3eAdWhirlRegister(s3eAdWhirlCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_ADWHIRL_HASH, S3E_ADWHIRL_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult s3eAdWhirlUnRegister(s3eAdWhirlCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_ADWHIRL_HASH, S3E_ADWHIRL_CALLBACK_MAX, cbid, fn);
}

void s3eAdWhirlRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[6];
    funcPtrs[0] = (void*)s3eAdWhirlRegister;
    funcPtrs[1] = (void*)s3eAdWhirlUnRegister;
    funcPtrs[2] = (void*)s3eAdWhirlStart;
    funcPtrs[3] = (void*)s3eAdWhirlRequestFreshAd;
    funcPtrs[4] = (void*)s3eAdWhirlShow;
    funcPtrs[5] = (void*)s3eAdWhirlHide;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[6] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eAdWhirl", funcPtrs, sizeof(funcPtrs), flags, s3eAdWhirlInit, s3eAdWhirlTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eAdWhirlStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eAdWhirlRegisterExt;
    return 0;
}

int g_s3eAdWhirlVal = s3eAdWhirlStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eAdWhirlRegisterExt();
}
#endif

#endif
