/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EADWHIRL_AUTODEFS_H
#define S3EADWHIRL_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADWHIRL_NAME "s3eAdWhirl"
#define S3E_EXT_ADWHIRL_HASH 0x8de9ae3b

#endif /* !S3EADWHIRL_AUTODEFS_H */
