/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eAdWhirl.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eAdWhirlRegister_t)(s3eAdWhirlCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eAdWhirlUnRegister_t)(s3eAdWhirlCallback cbid, s3eCallback fn);
typedef  s3eResult(*s3eAdWhirlStart_t)(const char* appKey);
typedef  s3eResult(*s3eAdWhirlRequestFreshAd_t)();
typedef  s3eResult(*s3eAdWhirlShow_t)();
typedef  s3eResult(*s3eAdWhirlHide_t)();

/**
 * struct that gets filled in by s3eAdWhirlRegister
 */
typedef struct s3eAdWhirlFuncs
{
    s3eAdWhirlRegister_t m_s3eAdWhirlRegister;
    s3eAdWhirlUnRegister_t m_s3eAdWhirlUnRegister;
    s3eAdWhirlStart_t m_s3eAdWhirlStart;
    s3eAdWhirlRequestFreshAd_t m_s3eAdWhirlRequestFreshAd;
    s3eAdWhirlShow_t m_s3eAdWhirlShow;
    s3eAdWhirlHide_t m_s3eAdWhirlHide;
} s3eAdWhirlFuncs;

static s3eAdWhirlFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x8de9ae3b, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eAdWhirl");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x8de9ae3b, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eAdWhirlAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eAdWhirlRegister(s3eAdWhirlCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl[0] func: s3eAdWhirlRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdWhirlRegister(cbid, fn, userData);
}

s3eResult s3eAdWhirlUnRegister(s3eAdWhirlCallback cbid, s3eCallback fn)
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl[1] func: s3eAdWhirlUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdWhirlUnRegister(cbid, fn);
}

s3eResult s3eAdWhirlStart(const char* appKey)
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl[2] func: s3eAdWhirlStart"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdWhirlStart(appKey);
}

s3eResult s3eAdWhirlRequestFreshAd()
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl[3] func: s3eAdWhirlRequestFreshAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdWhirlRequestFreshAd();
}

s3eResult s3eAdWhirlShow()
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl[4] func: s3eAdWhirlShow"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdWhirlShow();
}

s3eResult s3eAdWhirlHide()
{
    IwTrace(ADWHIRL_VERBOSE, ("calling s3eAdWhirl[5] func: s3eAdWhirlHide"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdWhirlHide();
}
